# TODO: Update/remove github secret?

apiVersion: k3d.io/v1alpha5
kind: Simple

# volumes:
#   # https://k3d.io/v5.7.4/faq/faq/#issues-with-btrfs
#   # -v /dev/mapper:/dev/mapper@all
#   - volume: /dev/mapper:/dev/mapper
#     nodeFilters:
#       - all:*

# Disable default registry endpoint to avoid pulling images from Docker Hub directly (testing cache)
# --k3s-arg "--disable-default-registry-endpoint@all:*"
# options:
#   k3s:
#     extraArgs:
#       - arg: "--disable-default-registry-endpoint"
#         nodeFilters:
#           - all:*

# Docker Hub Pull Rate Limit is 100 pulls per hour for anonymous users
# We can mitigate this by:
#  - using a pull-through cache (this config)
#    https://k3d.io/v5.8.3/usage/registries/#creating-a-registry-proxy-pull-through-registry
#  - using a personal access token (PAT) to authenticate (increase limit to 200 pulls per hour)
#    https://k3d.io/v5.8.3/faq/faq/#dockerhub-pull-rate-limit

# Pull-through cache for Docker Hub and GHCR
registries:
  create:
    name: k3d-docker.io
    proxy:
      remoteURL: https://registry-1.docker.io
      # username: "$DOCKERHUB_USERNAME"
      # password: "$DOCKERHUB_PASSWORD"
    volumes:
      - $HOME/.cache/registry/docker-io:/var/lib/registry
      # - $PWD/cache/docker-io:/var/lib/registry

  # use:
  #   - k3d-docker.io #:5001
  #   - k3d-ghcr.io   #:5002

  # https://github.com/k3d-io/k3d/issues/1548
  config: |
    mirrors:
      # Pull-through cache for Docker Hub
      "docker.io":
        endpoint:
          - http://k3d-docker.io:5000        # registry from this config file
          # - http://host.docker.internal:5001 # registry from host machine

      # Pull-through cache for GHCR
      "ghcr.io":
        endpoint:
          - http://k3d-ghcr.io:5000
          # - http://host.docker.internal:5002


# managed by k3d
# k3d registry create docker-io --proxy-remote-url https://registry-1.docker.io -v ~/.cache/registry/docker-io:/var/lib/registry --proxy-password <TOKEN>
# k3d registry create ghcr-io --proxy-remote-url https://ghcr.io -v ~/.cache/registry/ghcr-io:/var/lib/registry

# import from host machine
# k3d registry create docker.io --port 5001 --proxy-remote-url https://registry-1.docker.io --volume ~/.cache/registry/docker-io:/var/lib/registry --proxy-password <TOKEN>
# k3d registry create ghcr.io --port 5002 --proxy-remote-url https://ghcr.io --volume ~/.cache/registry/ghcr-io:/var/lib/registry
