apiVersion: k3d.io/v1alpha5
kind: Simple

# Define local registry caches
registries:
  # use:
    # - k3d-docker-io #:5000
    # - k3d-ghcr-io   #:5001

  config: |
    mirrors:
      # Pull-through cache for Docker Hub
      "docker.io":
        endpoint:
          - http://host.docker.internal:5001  # registry from host machine
          # - http://172.17.0.1:5001

      # Pull-through cache for GHCR
      "ghcr.io":
        endpoint:
          - http://host.docker.internal:5002

# k3d cluster create params:
# DOCKER_GW=$(docker network inspect bridge | jq -re '.[].IPAM.Config[].Gateway')
# --host-alias "$DOCKER_GW:host.docker.internal" \

# https://github.com/k3d-io/k3d/issues/1548
# k3d registry create docker.io --port 5001 --proxy-remote-url https://registry-1.docker.io --volume ~/.cache/registry/docker-io:/var/lib/registry
# k3d registry create ghcr.io --port 5002 --proxy-remote-url https://ghcr.io --volume ~/.cache/registry/ghcr-io:/var/lib/registry
