# Configure pull-through cache for Docker Hub (default) and GHCR (optional)
# https://k3d.io/v5.8.3/usage/registries/#creating-a-registry-proxy-pull-through-registry

# TODO:
# - Update/remove github secret?
# - Which directory to use for Cache (GH/self-hosted/local)
# - clean up :latest from cache

# - Docker cache is configured by default
# - GHCR cache is configured if k3d-ghcr.io registry exists

apiVersion: k3d.io/v1alpha5
kind: Simple

# Disable default registry endpoint to avoid pulling images from Docker Hub directly (testing cache)
# --k3s-arg "--disable-default-registry-endpoint@all:*"
# options:
#   k3s:
#     extraArgs:
#       - arg: "--disable-default-registry-endpoint"
#         nodeFilters:
#           - all:*

registries:
  create:
    name: k3d-docker.io
    proxy:
      remoteURL: https://registry-1.docker.io
      # Authenticate to Docker Hub (increase rate limit to 200 pulls per hour)
      username: "$DOCKERHUB_USERNAME"
      password: "$DOCKERHUB_PASSWORD"
    volumes:
      - $HOME/.cache/registry/docker-io:/var/lib/registry
      # - $PWD/cache/docker-io:/var/lib/registry

  config: |
    mirrors:
      # Pull-through cache for Docker Hub
      "docker.io":
        endpoint:
          - http://k3d-docker.io:5000
          # - http://host.docker.internal:5001

      # Pull-through cache for GHCR
      "ghcr.io":
        endpoint:
          - http://k3d-ghcr.io:5000
          # - http://host.docker.internal:5002

# Official
# k3d registry create docker-io --proxy-remote-url https://registry-1.docker.io -v ~/.cache/registry/docker-io:/var/lib/registry
# k3d registry create ghcr-io --proxy-remote-url https://ghcr.io -v ~/.cache/registry/ghcr-io:/var/lib/registry
