name: End-to-end tests

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  K3D_VERSION: # 'v5.6.3' - optionally pin version

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      # Install dependencies
      - name: K3D
        # wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG={{ env.K3D_VERSION }} sudo --preserve-env=TAG bash
        run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Bats
        run: sudo npm install -g bats
      - name: "Kwctl"
        uses: kubewarden/github-actions/kwctl-installer@main
        with:
          KWCTL_VERSION: latest

      # Devel helm charts (LOCAL)
      # - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      #   with:
      #     repository: {{ github.repository_owner }}/helm-charts
      #     sparse-checkout: charts

      - uses: ./
        with:
          # make: install tests uninstall
          make: install uninstall
        # env:
        #   CHARTS_LOCATION: ../charts
