name: End-to-end tests

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: "Kwctl"
        uses: kubewarden/github-actions/kwctl-installer@main
        with:
          KWCTL_VERSION: latest

      - name: Dependencies
        run: |
          sudo npm install -g bats
          wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          helm repo add kubewarden https://charts.kubewarden.io

      - name: Checkout tested PR
        uses: actions/checkout@v5
        with:
          submodules: "true"

      - name: Checkout Helm Charts
        uses: actions/checkout@v5
        with:
          repository: kubewarden/helm-charts
          sparse-checkout: charts
          path: helm-charts
          ref: main

      - name: Run Tests
        run: make install tests
        env:
          CHARTS_LOCATION: ./helm-charts/charts
